services:
  - type: web
    name: heart-disease-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash api/start.sh
    branch: main
    autoDeploy: true
    healthCheckPath: /
